SETUP:
    LEAi US, 0
    LEAi DS, 0
    LEAi UM, 0
    LEAi DM, 0
    LEAi UH12, 2
    LEAi DH12, 0
    LEAi UH24, 1
    LEAi DH24, 0
    LEAi AMPM, 0
    JMP COMECA
LOOP:
	LEA BaseTempo, IOSR
	CMPe JER, IOSR , 1
	JE COMECA
	JMP LOOP
COMECA:
    LEA SWs, IOSR
    CMPe JER, IOSR, 1
    JE CONFIGHORA
    LEA SWs, IOSR
    CMPe JER, IOSR, 2
    JE CONFIGMIN
    LEA SWs, IOSR
    CMPe JER, IOSR, 4
    JE 24h
    JMP 12h
TEMPO:
    ADDi US, US, 1
    CMPi JER, US, 9
    JB CDS
    CMPi JBR, DS, 5
    JB CUM
    CMPi JLR, UM, 9
    JB CDM
    CMPi AMPM, DM, 2
    -- SE A DEZENA FOR MAIOR QUE 2 PULA
CDS:
    LEAi US, 0
    ADDi DS, DS, 1
CUM:
    LEAi DS, 0
    ADDi UM, UM, 1
CDM:
    LEAi DM, 0
    ADDi UH12, UH12, 1
    ADDi UH24, UH24, 1
CUH12:
CUH24:
CDH24:
24h:
12h:
CONFIGHORA:
PROCUH:
AJUSTAH24:
CHECKUP2UH:
AJUSTADH2412:
AJUSTAD24H:
ENVIAUP7SEG:
ENVIA24H7SEG:
CONFIGMIN:
VOLTARCHECKDM:
AJUSTAMD:
AJUSTAMU:
ENVIAM7SEG:
