SETUP:
    LEAi US, 0
    LEAi DS, 0
    LEAi UM, 0
    LEAi DM, 0
    LEAi UH12, 2
    LEAi DH12, 0
    LEAi UH24, 1
    LEAi DH24, 0
    LEAi AMPM, 0
    JMP COMECA
LOOP:
	LEA BaseTempo, IOSR
	CMPe JER, IOSR, 1
	JE COMECA
	JMP LOOP
COMECA:
    LEA SWs, IOSR
    CMPe JER, IOSR, 1
    JE CONFIGHORA
    LEA SWs, IOSR
    CMPe JER, IOSR, 2
    JE CONFIGMIN
    LEA SWs, IOSR
    CMPe JER, IOSR, 4
    JE 24h
    JMP 12h
TEMPO:
    ADDi US, US, 1
    CMPi JLER, US, 9
    JB CDS
CDS:
    LEAi US, 0
    ADDi DS, DS, 1
    CMPi JLER, DS, 5
    JB CUM
CUM:
    LEAi DS, 0
    ADDi UM, UM, 1
    CMPi JLER, UM, 9
    JB CDM
CDM:
    LEAi UM, 1
    ADDi DM, DM, 1
    CMPi JLER, DM, 5
    JB CUH12
CUH12:
    LEAi DM, 0
    ADDi UH12, UH12, 1
    ADDi UH24, UH24, 1
    CMPi JLER, UH12, 2
    JB CDH12
CDH12:
    CMPi JLER, DH12, 0
    JB CDH122
CDH122:
    LEAi UH12, 1
    LEAi DH12, 0
    CMPi JLER, UH12, 9
    JB CDH123
CDH123:
    LEAi UH12, 0
    ADDi DH12, DH12, 1
    CMPi JLER, UH24, 3
    JB CUH24
    JMP CUH12
CUH24:
    CMPi JLER, DH24, 1
    JB CDH24
CDH24:
    LEAi UH24, 0
    ADDi, DH24, DH24, 0
    CMPi JLER, UH24, 9
    JB CUH242
CUH242:
    LEAi UH24, 0
    ADDi DH24, DH24, 1
    CMPi JLER, DH24, 2
    JB CDH242
CDH242:
    LEAi DH24, 0
    JMP LOOP
24h:
    LOAD US, 7US
    LOAD DS, 7DS
    LOAD UM, 7UM
    LOAD DM, 7DM
    LOAD UH24, 7UH
    LOAD DH24, 7DH
    JMP TEMPO
12h:
    LOAD US, 7US
    LOAD DS, 7DS
    LOAD UM, 7UM
    LOAD DM, 7DM
    LOAD UH12, 7UH
    LOAD DH12, 7DH
    JMP TEMPO
CONFIGHORA:
    LEA KEYs, IOSR
    CMPe JER, IOSR, 1
    JE PROCUH
    JMP CHECKUP2UH
PROCUH:
    ADDi UH12, UH12, 1
    ADDi UH24, UH24, 1
    CMPi JLER, UH12, 9
    JB AJUSTAH24
AJUSTAH24:
    LEAi UH12, 0 
    CMPi UH24, JLER, 9
    JB CHECKUP2UH
CHECKUP2UH:
    LEAi UH24, 0
    LEA KEYs, IOSR
    CMPe JER, IOSR, 2
    JE AJUSTADH2412
    JMP LOOP
AJUSTADH2412:
    ADDi DH12, DH12, 1
    ADDi DH24, DH24, 1
    CMPi JLER, DH12, 1
    JB AJUSTAD24H
AJUSTAD24H:
    LEAi DH12, 0
    CMPi JLER, DH24, 2
    JB ENVIAUP7SEG
ENVIAUP7SEG:
    LEAi DH24, 0
    LEA SWs, IOSR
    CMPe JER, IOSR, 4
    JE ENVIA24H7SEG
    LOAD UH12, 7UH
    LOAD DH12, 7DH
    JMP LOOP
ENVIA24H7SEG:
    LOAD UH24, 7UH
    LOAD DH24, 7DH
    JMP LOOP
CONFIGMIN:
    LEA KEYs, IOSR
    CMPe JER, IOSR, 1
    JE AJUSTAMD
VOLTARCHECKDM:
    LEA KEYs, IOSR
    CMPe JER, IOSR, 2
    JE AJUSTAMU
    JMP LOOP
AJUSTAMD:
    ADDi UM, UM, 1
    CMPi JLER, UM, 9
    JB VOLTARCHECKDM
    LEAi UM, 0
    JMP VOLTARCHECKDM
AJUSTAMU:
    ADDi DM, DM, 1
    CMPi DM, JLER, 5
    JB ENVIAM7SEG
ENVIAM7SEG:
    LEAi DM, 0
    LOAD UM, 7UM
    LOAD DM, 7DM
    JMP LOOP